spring:
  mvc: 
    throw-exception-if-no-handler-found: true
  jackson:
    deserialization: 
      fail-on-missing-creator-properties: 'false'
  datasource:
    url: jdbc:mysql://localhost:3306/CALPULLIX_VIRTUAL_MANAGER_ASSISTANT?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: adminadmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: juan.pedraza.escom12@gmail.com
    password: Escomjc22!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  boot:
    admin:
      client:
        url: http://localhost:9550

hystrix:
  threadpool:
    default:
      coreSize: 35
      maximumSize: 35
  command: 
    invoke: 
      circuitBreaker:
        requestVolumeThreshold: 35
        sleepWindowInMilliseconds: 1000
      metrics:
        rollingStatus:
          timeInMilliseconds: 60000
      execution: 
        isolation: 
          thread:
            timeoutInMilliseconds: 10000
          semaphore: 
            maxConcurrentRequest: 500
            
logging:
  level:
    #reactor.netty: TRACE
    org:
      springframework.web: INFO
      springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      springframework.web.servlet.DispatcherServlet: DEBUG
      springframework.cloud.sleuth: DEBUG
    com.calpullix.service.login: DEBUG
  pattern:
    level: '[%X{data}%thread][%X{X-B3-TraceId:-}]-%5p'
    
    
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  health:
    defaults:
      enabled: true
    jms:
      enabled: false 

eureka:
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka   
  
app:
  message-error-location-body: Body
  path-login: /login
  path-login-token: /login/token
  
jwt:
  secret-key: javainuse
      
      
  
     
 
