spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CALPULLIX_VIRTUAL_MANAGER_ASSISTANT?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: adminadmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  
  
     
                  
logging:
  level:
    org:
      springframework.web: INFO
      springframework.web.servlet.DispatcherServlet: DEBUG
      springframework.cloud.sleuth: DEBUG
    com.calpullix: DEBUG
  pattern:
    level: '[%X{data}%thread][%X{X-B3-TraceId:-}]-%5p'
    
    
management:
  endpoints:
    web:
      base-path: /actuator
  helath:
    defaults:
      enabled: true
    jms:
      enabled: false 
  
app:
  query-top-five-profile-products: SELECT P.id as idProduct, COUNT(*) as quantityPurchases FROM Product_Branch as PB, Product_History as PH, Product as P, Customers as C WHERE PB.idCustomer = C.id AND C.id = ? AND PB.idProductHistory = PH.id AND PH.idProduct = P.id GROUP BY P.id ORDER BY COUNT(*) DESC LIMIT 5;
  
      
      
  
     
 
