spring:
  mvc: 
    throw-exception-if-no-handler-found: true
  jackson:
    deserialization: 
      fail-on-missing-creator-properties: 'false'
  datasource:
    url: jdbc:mysql://localhost:3306/CALPULLIX_VIRTUAL_MANAGER_ASSISTANT?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: adminadmin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  boot:
    admin:
      client:
        url: http://localhost:9550
   


hystrix:
  threadpool:
    default:
      coreSize: 35
      maximumSize: 35
  command: 
    invoke: 
      circuitBreaker:
        requestVolumeThreshold: 35
        sleepWindowInMilliseconds: 1000
      metrics:
        rollingStatus:
          timeInMilliseconds: 60000
      execution: 
        isolation: 
          thread:
            timeoutInMilliseconds: 10000
          semaphore: 
            maxConcurrentRequest: 500
            
logging:
  level:
    org:
      springframework.web: INFO
      springframework.web.servlet.DispatcherServlet: DEBUG
      springframework.cloud.sleuth: DEBUG
    com.calpullix.service.login: DEBUG
  pattern:
    level: '[%X{data}%thread][%X{X-B3-TraceId:-}]-%5p'
    
    
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  health:
    defaults:
      enabled: true
    jms:
      enabled: false 

eureka:
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka   
  
app:
  message-error-location-body: Body
  path-best-branch: /calpullix/best/branch
  path-get-branch: /calpullix/branch/retrieve
  path-get-branch-list: /calpullix/branch/list
  path-get-branch-dummy: /calpullix/branch/dummy
  pagination-size: 5
  procedure-name: calpullix_branch_information
      
      
  
